### ISSUE TITLE
Add error 014-0016

### ISSUE THREAD

**Issue by cheatfreak47** [ihaveamac/Kurisu#276]
This error isn't really documented on Nintendo's site, though, several cases of it appearing have been spotted from time to time.

It's currently believed the issue is caused by a particular set of circumstances occurring, amounting to both 3DS consoles using the same profile and crypto. (I.E., have the same folder names in the Nintendo 3DS folder on SD, have the same friend code, same NNID, etc.)

The usual cause for this error seems to be people performing a system transfer to perform DSiwareHax, and then restoring a NAND backup made on the source console from before the transfer took place, resulting in both 3DS consoles having the same profile. 

This error (014-0016) occurs during an attempted System Transfer (at the transfer of Built-In Software)  from the prior target system (now the source system) back to the prior source system (now the target system) which are both using the same crypto key, and share a profile (with the target system profile being detached from the console, server-side)

The solution is to format one of the consoles, (usually the current target system) once in 3DS System Settings before attempting the transfer again. This will change the crypto key and profile to a new one, allowing the transfer to take place properly.

**Comment by ihaveamac** [comment]
cec163d89feb2b0de63f7ea6606058721d4531a8
